version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/flask-cicd

hooks:
  AfterInstall:
    - location: scripts/start_server.sh
      timeout: 300
      runas: ec2-user

  ValidateService:
    - location: scripts/health_check.sh
      timeout: 30
      runas: ec2-user
